### ISSUE TITLE
Provide "-version" command for REPL users

### ISSUE THREAD

**Issue by jgabaut** [jedrzejboczar/easy-repl#11]
Hi, I've forked the repo just to add a version identifier to the code (I just could not find how to reference the Cargo one, which would be better) and a function to get it.

I wanted this so that in my user REPL you could also have `version` command and differentiate the two.

My fork is dirty with my name and the identifier is not properly defined as I said.

Also, I bumped the version number a couple of times by accident.
Aaand disabled hints by default, but obviously this won't last.

If you think this could be added, let me know, I can add a commit or squash everything and clean the unwanted traces.

[Diff](https://github.com/jedrzejboczar/easy-repl/compare/master...jgabaut:easy-repl:master)

**Comment by jedrzejboczar** [comment]
Hi, if you want to avoid hard-coding the version you can use the `CARGO_PKG_VERSION` as described [here](https://stackoverflow.com/a/27841363). 

After some thinking I would say that it's not something to be added to the main repo. Most users wouldn't want to have the version of easy-repl library shown in their application REPL. Rather, they might want the version of their application, but this is something they can add when building their REPL. Anyway, thanks for the idea :)
