### ISSUE TITLE
`PathBuf` filename completion does not work?

### ISSUE THREAD

**Issue by jkorinth** [jedrzejboczar/easy-repl#12]
Example:
```rust
let cmd = command! {
    "open",
    (filename: PathBuf) => { ... },
};
```

When run in the default REPL, there's no autocompletion for relative paths, e.g., 
```
> open .
```
Reading [this code](https://github.com/jedrzejboczar/easy-repl/blob/01ba4376ef53c220012dc1b4c4b131269c847798/src/completion.rs#L4) I assumed it would offer completion hints?

**Comment by jedrzejboczar** [comment]
You need to enable filename completion which is [disabled by default](https://github.com/jedrzejboczar/easy-repl/blob/01ba4376ef53c220012dc1b4c4b131269c847798/src/repl.rs#L103), e.g.
```rust
let mut repl = Repl::builder()
    // ...
    .with_filename_completion(true)
    .build()
```

**Comment by jkorinth** [comment]
Perfect, works, thanks!
