### ISSUE TITLE
Macro seems to be broken, relies on importing `anyhow`.

### ISSUE THREAD

**Issue by jeremysalwen** [jedrzejboczar/easy-repl#4]
If you don't add `anyhow` as a dependency and use it in your module, then easy-repl will fail.  Seems like a simple undeclared dependency that you didn't notice, since you always used `anyhow` anyways.

**Comment by jedrzejboczar** [comment]
Thanks, good catch. This should be fixed with https://github.com/jedrzejboczar/easy-repl/commit/bb3b8227dd0150a535f6a0b9972194cddf201f27.

**Comment by femtomc** [comment]
@jedrzejboczar I ran into this today -- did you release a new version with this fix?

**Comment by jedrzejboczar** [comment]
@femtomc Oh, actually I didn't. I'll release it in a moment.
